#!/usr/bin/env python3
"""Bundle confirmed 175 mm captures and the parameter-identified control log. Stdlib only."""
import csv
import hashlib
import json
import math
from pathlib import Path
from statistics import median

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent
DATA = ROOT / 'pendulum_characterization/175mm_14p2g/2026-09-15'

def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def wrap(angle):
    return math.atan2(math.sin(angle), math.cos(angle))

def build():
    fit = json.loads((DATA / 'controller_fit.json').read_text())
    config = json.loads((ROOT / 'cartpole_controller_config.json').read_text())
    captures = []
    for run in fit['runs']:
        path = ROOT / run['source']
        if digest(path) != run['sha256']:
            raise ValueError(f'Source hash mismatch: {path}')
        rows = list(csv.DictReader(path.open()))
        zero = median(float(r['theta']) for r in rows[-1000:])
        t0 = float(rows[0]['t_us'])
        points = [[(float(r['t_us'])-t0)*1e-6, wrap(float(r['theta'])-zero)] for r in rows]
        start = min(c['start_s'] for c in run['cycles'])
        idx = min(range(len(points)), key=lambda i: abs(points[i][0]-start))
        # These are measured peak windows, with omega=0 as an explicit approximation.
        window = [[round(t-start, 6), round(q, 7)] for t, q in points[idx::5] if t <= start+5]
        captures.append(dict(name=path.stem, source=run['source'], sha256=run['sha256'],
                             period_s=run['period_s'], length_m=run['effective_length_m'],
                             damping=run['equivalent_viscous_decay_per_s'], cycle_count=run['cycle_count'],
                             start_s=start, window=window,
                             full=[[round(t,5),round(q,7)] for t,q in points[::10]]))
    recorded = OUT / 'recorded_20t_trial.json'
    log_bundle = json.loads(recorded.read_text())
    log_bundle['sha256'] = digest(recorded)
    bundle = dict(schema=1, configuration=json.loads((DATA/'configuration.json').read_text()),
                  controller=config, fit={k:v for k,v in fit.items() if k!='runs'},
                  captures=captures, control_log=log_bundle,
                  recorded_cases=json.loads((ROOT/'analysis/data_informed_cases.json').read_text()),
                  sources=[dict(path=str(p.relative_to(ROOT)),sha256=digest(p)) for p in
                           [DATA/'controller_fit.json', DATA/'configuration.json',ROOT/'cartpole_controller_config.json',
                            ROOT/'swingup/cart_mechanics.h',ROOT/'swingup/swing_controller.h',ROOT/'swingup/cart_motion.h',ROOT/'swingup/spin_recovery.h',ROOT/'swingup/upright_session.h',ROOT/'swingup/encoder_reference.h',ROOT/'swingup/serial_frame.h']])
    (OUT/'data.js').write_text('/* Generated by build_data.py; raw sources are unchanged. */\nwindow.PENDULUM_DATA = '+json.dumps(bundle,separators=(',',':'))+';\n')
    print(json.dumps(dict(captures=len(captures),cycles=fit['total_cycles'],control_log=log_bundle['summary']),indent=2))

if __name__=='__main__': build()
